# Generated by Django 3.0.8 on 2020-07-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'verbose_name': 'Профиль поставщика', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
