# Generated by Django 3.0.8 on 2020-08-10 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_phone',
                 models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('bank_details', models.CharField(blank=True, max_length=30, null=True, verbose_name='Реквизиты')),
                ('provider_name',
                 models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование компании')),
                ('provider_email',
                 models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email адресс компании')),
                ('provider_address',
                 models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес компании')),
                ('category',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Categories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
