# Generated by Django 3.0.8 on 2020-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200731_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='provider_address',
            field=models.CharField(default=1, max_length=250, verbose_name='Адрес компании'),
            preserve_default=False,
        ),
    ]
