# Generated by Django 3.0.8 on 2020-08-10 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(
                    message='Номер телефона имеет формат: +777777777, от 9 до 15 символов', regex='^\\+?1?\\d{9,15}$')],
                                                  verbose_name='Номер телефона')),
                ('client_name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('client_surname', models.CharField(max_length=128, verbose_name='Фамилия клиента')),
                ('client_email', models.EmailField(max_length=128, verbose_name='E-mail клиента')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Сумма')),
                ('status', models.IntegerField(
                    choices=[(1, 'Новый'), (2, 'Формируется'), (3, 'Готов к выдаче'), (4, 'Получено'),
                             (5, 'Ошибка, обратитесь в службу поддержки')], default=1, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='QrCodesOrderVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('qr', models.ImageField(upload_to='qr_codes/', verbose_name='QR код')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders',
                                               verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'QR код подтверждения',
                'verbose_name_plural': 'QR коды подтверждения',
            },
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_one', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за единицу')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Orders',
                                            verbose_name='Заказ')),
                ('product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Products',
                                   verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
