# Generated by Django 3.0.8 on 2020-08-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('form', 'Формируется'), ('ready', 'Готов к выдаче'),
                                            ('received', 'Получено'),
                                            ('error', 'Ошибка, обратитесь в службу поддержки')], default='new',
                                   max_length=255, verbose_name='Статус заказа'),
        ),
    ]
