# Generated by Django 3.0.8 on 2020-08-17 03:32

from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_auto_20200810_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('received', 'Получено'), ('form', 'Формируется'),
                                            ('error', 'Ошибка, обратитесь в службу поддержки'),
                                            ('ready', 'Готов к выдаче')], default=orders.models.StatusOrders['new'],
                                   max_length=255, verbose_name='Статус заказа'),
        ),
    ]
