# Generated by Django 3.0.8 on 2020-08-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_auto_20200801_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodesOrderVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('qr', models.ImageField(upload_to='qr_codes/', verbose_name='QR код')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders',
                                               verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'QR код подтверждения',
                'verbose_name_plural': 'QR коды подтверждения',
            },
        ),
    ]
