# Generated by Django 3.0.8 on 2020-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_auto_20200817_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('received', 'Получено'), ('form', 'Формируется'),
                                            ('error', 'Ошибка, обратитесь в службу поддержки'),
                                            ('ready', 'Готов к выдаче')], default='new', max_length=255,
                                   verbose_name='Статус заказа'),
        ),
    ]
