# Generated by Django 3.0.8 on 2020-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_auto_20200915_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='price_for_one',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Цена за единицу'),
        ),
    ]
