# Generated by Django 3.0.8 on 2020-08-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_providerprofile'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.IntegerField(choices=[(1, 'Новый'), (2, 'Доставлено')], default=1, verbose_name='Статус')),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество позиций')),
                ('total_price',
                 models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProviderProfile',
                                   verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='ProductsInDeliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.Deliveries',
                                               verbose_name='Поставка')),
                ('product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Products',
                                   verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в поставке',
                'verbose_name_plural': 'Товары в поставке',
            },
        ),
    ]
