# Generated by Django 3.0.8 on 2020-08-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('received', 'Получено')], default='new', max_length=255,
                                   verbose_name='Статус'),
        ),
    ]
