# Generated by Django 3.0.8 on 2020-08-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('deliveries', '0003_auto_20200801_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество позиций'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма'),
        ),
    ]
